import numpy as np
from matplotlib import pyplot as plt
from scipy.stats import norm

from clustering import uniclustering
from information import criteria
from p2 import low_count_high_variance, low_count_low_variance, high_count_low_variance, high_count_high_variance

if __name__ == "__main__":
    data1 = low_count_low_variance()
    data2 = low_count_high_variance()
    data3 = high_count_low_variance()
    data4 = high_count_high_variance()

    Z1 = uniclustering.ward_linkage(data1)
    Z2 = uniclustering.ward_linkage(data2)
    Z3 = uniclustering.ward_linkage(data3)
    Z4 = uniclustering.ward_linkage(data4)

    n = Z1.shape[0]

    x1 = np.gradient(Z1[:, 2])
    x2 = np.gradient(Z2[:, 2])
    x3 = np.gradient(Z3[:, 2])
    x4 = np.gradient(Z4[:, 2])

    y1 = np.gradient(criteria.calculate_bic_vector(data1, Z1))
    y2 = np.gradient(criteria.calculate_bic_vector(data2, Z2))
    y3 = np.gradient(criteria.calculate_bic_vector(data3, Z3))
    y4 = np.gradient(criteria.calculate_bic_vector(data4, Z4))

    r1 = np.linalg.norm(np.vstack([x1, y1]), axis=0)
    r2 = np.linalg.norm(np.vstack([x2, y2]), axis=0)
    r3 = np.linalg.norm(np.vstack([x3, y3]), axis=0)
    r4 = np.linalg.norm(np.vstack([x4, y4]), axis=0)

    z1 = (r1 - np.mean(r1)) / np.std(r1)
    z2 = (r2 - np.mean(r2)) / np.std(r2)
    z3 = (r3 - np.mean(r3)) / np.std(r3)
    z4 = (r4 - np.mean(r4)) / np.std(r4)

    plt.subplots(2, 2)
    plt.title("X Logplot")
    plt.subplot(2, 2, 1)
    plt.title("LcLv")
    plt.plot(np.arange(0, n), np.log(x1))
    plt.subplot(2, 2, 2)
    plt.title("LcHv")
    plt.plot(np.arange(0, n), np.log(x2))
    plt.subplot(2, 2, 3)
    plt.title("HcLv")
    plt.plot(np.arange(0, n), np.log(x3))
    plt.subplot(2, 2, 4)
    plt.title("HcHv")
    plt.plot(np.arange(0, n), np.log(x4))
    plt.show()

    plt.subplots(2, 2)
    plt.title("Y")
    plt.subplot(2, 2, 1)
    plt.title("LcLv")
    plt.plot(np.arange(0, n), y1)
    plt.subplot(2, 2, 2)
    plt.title("LcHv")
    plt.plot(np.arange(0, n), y2)
    plt.subplot(2, 2, 3)
    plt.title("HcLv")
    plt.plot(np.arange(0, n), y3)
    plt.subplot(2, 2, 4)
    plt.title("HcHv")
    plt.plot(np.arange(0, n), y4)
    plt.show()

    plt.subplots(2, 2)
    plt.title("BICESS")
    plt.subplot(2, 2, 1)
    plt.title("LcLv")
    plt.plot(x1, y1)
    plt.subplot(2, 2, 2)
    plt.title("LcHv")
    plt.plot(x2, y2)
    plt.subplot(2, 2, 3)
    plt.title("HcLv")
    plt.plot(x3, y3)
    plt.subplot(2, 2, 4)
    plt.title("HcHv")
    plt.plot(x4, y4)
    plt.show()

    plt.subplots(2, 2)
    plt.title("Z")
    plt.subplot(2, 2, 1)
    plt.title("LcLv")
    plt.plot(np.arange(0, n), z1)
    plt.ylim(-5, 5)
    plt.subplot(2, 2, 2)
    plt.title("LcHv")
    plt.plot(np.arange(0, n), z2)
    plt.ylim(-5, 5)
    plt.subplot(2, 2, 3)
    plt.title("HcLv")
    plt.plot(np.arange(0, n), z3)
    plt.ylim(-5, 5)
    plt.subplot(2, 2, 4)
    plt.title("HcHv")
    plt.plot(np.arange(0, n), z4)
    plt.ylim(-5, 5)
    plt.show()

    plt.subplots(2, 2)
    plt.subplot(2, 2, 1)
    plt.title("LcLv (Z Zoomed)")
    plt.plot(np.arange(0, n)[-100:], z1[-100:])
    plt.ylim(-5, 5)
    plt.subplot(2, 2, 2)
    plt.title("LcHv")
    plt.plot(np.arange(0, n)[-100:], z2[-100:])
    plt.ylim(-5, 5)
    plt.subplot(2, 2, 3)
    plt.title("HcLv")
    plt.plot(np.arange(0, n)[-100:], z3[-100:])
    plt.ylim(-5, 5)
    plt.subplot(2, 2, 4)
    plt.title("HcHv")
    plt.plot(np.arange(0, n)[-100:], z4[-100:])
    plt.ylim(-5, 5)
    plt.show()
